export enum ErrorCode {
  CODE_COOLDOWN = 'CODE_COOLDOWN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  CODE_EXPIRED = 'CODE_EXPIRED',
  INVALID_CODE = 'INVALID_CODE',
  INVALID_TOKEN = 'INVALID_TOKEN',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  CUSTOM_NAME_ALREADY_EXISTS = 'CUSTOM_NAME_ALREADY_EXISTS',
  NO_CHANGES_DETECTED = 'NO_CHANGES_DETECTED',
  USER_UPDATE_ERROR = 'USER_UPDATE_ERROR',
  USER_DELETE_ERROR = 'USER_DELETE_ERROR',
}
