export enum ErrorCode {
  CODE_COOLDOWN = 'CODE_COOLDOWN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  CODE_EXPIRED = 'CODE_EXPIRED',
  INVALID_CODE = 'INVALID_CODE',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
}
