export enum ErrorCode {
  CODE_COOLDOWN = 'CODE_COOLDOWN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  CODE_EXPIRED = 'CODE_EXPIRED',
  INVALID_CODE = 'INVALID_CODE',
  INVALID_TOKEN = 'INVALID_TOKEN',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
}
